# application.yml
server:
  port: 8082

spring:
  application:
    name: POST-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:password123@localhost:27017/social_media_users?authSource=admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  kafka:
    bootstrap-servers: localhost:9094

upload:
  path: /app/uploads

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    metadata-map:
      management:
        port: ${server.port}


# Pagination defaults
spring.data.web.pageable:
  default-page-size: 20
  max-page-size: 100
